# -*- coding: utf-8 -*-
"""
@Auth ： Fanghe.Lin
@File ：SpecConfig.py
@IDE ：PyCharm
@Time ： 2023/11/13 11:24
@Institution: Hikvision, China
"""

# 结果处理与比对字典
resultHandle = {
            "深度学习框架": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "浏览器": ['self.resHandleGeneral_2', 'self.resCompGeneral_2', [' '], None],
            "恢复出厂设置": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "开放能力": ['self.resHandleGeneral_2', 'self.resCompGeneral_2', None, None],
            "开放资源规格": ['self.resHandleGeneral_2', 'self.resCompGeneral_2', [' '], None],
            "开发语言": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "Smart事件": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "最大分辨率": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, ['×', 'x']],
            "聚焦模式": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "P/N制": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', ['制'], None],
            "预置点": ['self.resHandleGeneral_3', 'self.resCompGeneral_3', None, '(\d+)'],
            "快门": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', [' ', ',', '，', 's'], ['~','to']],
            "普通事件": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "数字变倍": ['self.resHandleGeneral_3', 'self.resCompGeneral_3', None, '(\d+)'],
            "码率控制": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "音频压缩标准": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "音频压缩码率": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', ['\(', '\)', '\（', '\）', '\s'], None],
            "视频压缩码率": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, ['~', 'to']],
            "视频压缩标准": ['self.resHandleGeneral_2', 'self.resCompGeneral_2', None, None],
            "水尺识别": ['self.resHandleGeneral_2', 'self.resCompGeneral_2', None, None],
            "H.264编码类型": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "H.265编码类型": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "同时预览路数": ['self.resHandleGeneral_3', 'self.resCompGeneral_3', None, '(\d+)'],
            "用户管理": ['self.resHandleGeneral_3', 'self.resCompGeneral_3', None, '(\d+)个'],
            "其他功能": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "低功耗协议": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "主码流帧率分辨率": ['self.resHandleGeneral_2', 'self.resCompGeneral_2', [' '], None],
            "子码流帧率分辨率": ['self.resHandleGeneral_2', 'self.resCompGeneral_2', [' '], None],
            "第三码流帧率分辨率": ['self.resHandleGeneral_2', 'self.resCompGeneral_2', [' '], None],
            "第四码流帧率分辨率": ['self.resHandleGeneral_2', 'self.resCompGeneral_2', [' '], None],
            "第五码流帧率分辨率": ['self.resHandleGeneral_2', 'self.resCompGeneral_2', [' '], None],
            "守望功能": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "定时任务": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "图像增强": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "图像设置": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', ['通过客户端或者浏览器可调'], None],
            "图像防抖": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "日夜转换模式": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "隐私保护": ['self.resHandleGeneral_2', 'self.resCompGeneral_2', ['【全景】', '【细节】'], None],  # 这条可能需修改
            "接口协议": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "客户端": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', ['海康互联'], None],
            "网络存储": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', ['均支持', '支持', "\/", '\(', '\（', '\)', '\）', ' '],None],# 可能还是有点问题
            "网络协议": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', None, None],
            "音频采样率": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', ['\s'], None],
            "ROI": ['self.resHandleGeneral_1', 'self.resCompGeneral_1', ['\n'], None],
            "网页客户端语言":['self.resHandleGeneral_2', 'self.resCompGeneral_2', [' ', '\(', '\)'], None],
        }

# 产品参数字典
'''该字典中的规格项目的比对结果均输出Check
FLAG = 0：输出NT
FLAG = 1：输出设备能力值
'''
ProductParamDict = {'带包装重量': 0, '包装尺寸': 0, '设备重量': 0, '水平范围': 0, '垂直范围': 0, '水平速度': 0, '垂直速度': 0, '调节角度': 0,
                    '其他功能': 1, '海外ANPR车牌': 1, '车辆抓拍': 1, '岗位值守检测': 1, '高空抛物检测': 1, '工服检测': 1, '垃圾检测': 1,
                    '明厨亮灶': 1,
                    # '室内消防通道占用': 1,
                    '智慧城管': 1, '月台管理': 1, '热度图': 1, '车位管理': 1, '客流统计': 1, '人员密度': 1,
                    '人数统计': 1, '智慧课堂': 1, '人脸抓拍': 1, '全结构化': 1, '智能交通': 1, '拥挤检测': 1, "水尺识别": 1, "人脸抓拍": 1}

# 固定写法的规格项
FixedOutputDict = {'深度学习框架': '该参数项内容为项目经理填写的固定值，若为F项，直接提交缺陷!',
                   '浏览器': '固定写法',
                    '恢复出厂设置': '该参数项内容为项目经理填写的固定值，若为F项，直接提交缺陷!',
                    '开放能力': '该参数项内容为项目经理填写的固定值，若为F项，直接提交缺陷!',
                   '开发语言': '该参数项内容为项目经理填写的固定值，若为F项，直接提交缺陷!',
                   '其他功能':'【一键恢复,防闪烁,心跳,flash日志,邮箱重置密码,像素计算器】为固定输出，请手动确认这几项功能！',
                    'SVC': '自动化无法判断不同编码能力下的SVC能力，仅输出【支持/不支持】',
                    '车辆抓拍': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '岗位值守检测': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '高空抛物检测': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '工服检测': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '垃圾检测': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '明厨亮灶': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    # '室内消防通道占用': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '智慧城管': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '月台管理': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '人脸抓拍': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '热度图': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '全抓拍': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '车位管理': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '客流统计': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '人员密度': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '人数统计': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '智慧课堂': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '海外ANPR车牌': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '人数统计': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '智能交通': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '全结构化': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '人数统计': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    '人脸比对': '仅判断支持/不支持，需要对应设备，后续根据需求添加详细规格参数',
                    "透雾": "是否支持光学透雾需根据需求自行确认",
                    "客户端": "1)若SPEC值包含【海康互联】，且设备支持【萤石】，比对结果为F时不用提缺陷;\n2)英文设备需自行确认以下能力：Hik-Central;Hik-ProConnect;iVMS-4500;iVMS-5200!",
                    "数字变倍": '该规格项为【数字变倍】!',
                    }

# 测试用例
SpecItemDict = {"深度学习框架": 'self.getDeepLearnFramework()',
                "浏览器": 'self.getChrome()',
                "恢复出厂设置": 'self.getReset()',
                "开放能力": 'self.getOpenCapability()',
                "开放资源规格": 'self.getopenAIParms()',
                "开发语言": 'self.getBuildLanguage()',
                "Smart事件": 'self.getSmartCap(self.IntegSupportList)',
                "最大分辨率": 'self.getMaxResolution()',
                "聚焦模式": 'self.getFocusMode()',
                "P/N制": 'self.getPNCap()',
                "断电记忆": 'self.getPowerOutMemory()',
                "预置点": 'self.getPTZPresetNum()',
                "快门": 'self.getShutterCap()',
                "普通事件": 'self.getEventCap()',
                "数字变倍": 'self.getImageZoomLimitRatio()',
                "人脸抓拍": 'self.getIntelfacesnap(self.IntegSupportList)',
                "SVC": 'self.getSVC()',
                "音频压缩标准": 'self.getAudioCodeType()',
                "音频压缩码率": 'self.getAudioaudioBitRate()',
                "码率控制": 'self.getVideoCompressionCodingrate()',
                "区域裁剪": 'self.getregionClip()',
                "视频压缩码率": 'self.getvbrUpperCap()',
                "视频压缩标准": 'self.getVideoCodec()',
                "水尺识别": 'self.getIntelwatergauge(self.IntegSupportList)',
                "3D定位": 'self.getPTZPosition3D()',
                "环境噪声过滤": 'self.getAudioNoiserCap()',
                "韦根": 'self.getWiegand()',
                "网页客户端语言": 'self.getWebLanguage()',
                "防破坏报警": 'self.getvandalProofAlarm()',
                "解码模式": 'self.getDECODEMODE()',
                "在线升级": 'self.getupgradeFlag()',
                "云台旋转": 'self.getPTRZ()',
                "H.264编码类型": 'self.getH264()',
                "H.265编码类型": 'self.getH265()',
                "同时预览路数": 'self.getSecurityPreviewNum()',
                "用户管理": 'self.getSystemUserCap()',
                "其他功能": 'self.getCommonFunctions()',
                "低功耗协议": 'self.getlowpower()',
                "主码流帧率分辨率": 'self.getsmainFrameAndColution()',
                "子码流帧率分辨率": 'self.getsubFrameAndColution()',
                "第三码流帧率分辨率": 'self.getthirdFrameAndColution()',
                "第四码流帧率分辨率": 'self.getfourFrameAndColution()',
                "第五码流帧率分辨率": 'self.getFiveFrameAndColution()',
                "海外ANPR车牌": 'self.getANPR()',
                "车辆抓拍": 'self.getVehicleCapture()',
                "岗位值守检测": 'self.getDismissionSleeping()',
                "高空抛物检测": 'self.getobjectsThrownDetection()',
                "工服检测": 'self.getWorkingClothesDetection()',
                "垃圾检测": 'self.getGarbageDetection()',
                "明厨亮灶": 'self.getKitchenHygieneDetection()',
                "室内消防通道占用": 'self.getIndoorFirePassageDetection()',
                "智慧城管": 'self.getcityManagement()',
                "月台管理": 'self.getHPPeopleDetection()',
                "热度图": 'self.getheatmap()',
                "全抓拍": 'self.getobjectsThrownDetection()',
                "车位管理": 'self.getPackingSpaceRecognition()',
                "客流统计": 'self.getcameraGroupPeopleCounting()',
                "人员密度": 'self.getPersonDensityDetection()',
                "人数统计": 'self.getframesPeopleCounting()',
                "智慧课堂": 'self.getSmartTeacherAndStudentBehavior()',
                # "显示模式": self.getDisplayMODE(),
                "道路监控": 'self.getIntelRoadDetection(self.IntegSupportList)',
                "比例变倍": 'self.getPTZproportionalpanCap()',
                "预置点视频冻结": 'self.getPTZImageFreeze()',
                "花样扫描": 'self.getPTZPatternNum()',
                "守望功能": 'self.getPTZparkactionCap()',
                "巡航扫描": 'self.getPTZPatrolNum()',
                "方位角信息显示": 'self.getPTZOSDDisplay()',
                "定时任务": 'self.getPTZTimeTaskList()',
                "ROI": 'self.getVideoROICap()',
                "透雾": 'self.getImageDehaze()',
                "图像增强": 'self.getImageStrong()',
                "图像参数切换": 'self.getImagedisplayParamSwitch()',
                "图像设置": 'self.getimageCap()',
                "图像防抖": 'self.getEIS_OIS()',
                "图片叠加": 'self.getImagOverlaye()',
                "日夜转换模式": 'self.getImageircutFilter()',
                "区域曝光": 'self.getImageRegionalExposure()',
                "区域聚焦": 'self.getImageRegionalFocus()',
                "隐私保护": 'self.getPrivacyMaskCap()',
                "接口协议": 'self.getNetWorkApiCap()',
                "客户端": 'self.getNetWorkEzvizCap()',
                "网络存储": 'self.getNetWorkStrogeNas()',
                "网络协议": 'self.getNetWorkThirApi()',
                "音频采样率": 'self.getAudioSamplingRate()',
                "设备重量": 'self.getWeight()',
                "包装尺寸": 'self.getPackageSize()',
                "带包装重量": 'self.getPackingSize()',
                "水平范围": 'self.getHorizontalExtent()',
                "垂直范围": 'self.getVerticalRange()',
                "水平速度": 'self.getHorizontalVelocity()',
                "垂直速度": 'self.getVerticalVelocity()',
                "调节角度": 'self.getAdjustAngle()',
                "全结构化": 'self.getMixedTargetDetection()',
                "智能交通": 'self.getIntelligentTraffic()',
                "慢快门": 'self.getSlowShutterCap()',
                "拥挤检测": 'self.getCongestionDetection()',
                "人脸比对": 'self.getfaceContrast()',
                }

# 新增名称兼容字典
itemNameCheck = {
    '隐私保护': '隐私保护',
    '隐私遮蔽': '隐私保护',
    '最大分辨率': '最大分辨率',
    '最大图像尺寸': '最大分辨率',
    '同时预览路数': '同时预览路数',
    '最大取流路数': '同时预览路数',
    '网络协议':'网络协议',
    '支持协议':'网络协议',
    '其他功能':'其他功能',
    '通用功能':'其他功能',
    '数字变倍': '数字变倍',
    '变倍': '数字变倍',
    '环境噪声过滤': '环境噪声过滤',
    '音频环境噪声过滤': '环境噪声过滤',
    '日夜转换模式': '日夜转换模式',
    '日夜转换方式': '日夜转换模式',
    '全结构化': '全结构化',
    '混合目标检测': '全结构化',
    '规则配置': '规则配置',
    '事件规则': '规则配置',
    '岗位值守检测': '岗位值守检测',
    '在离岗检测': '岗位值守检测',
    '网页客户端语言': '网页客户端语言',
    'Web端语言': '网页客户端语言',
    'H.264':'H.264编码类型',
    'H.264编码类型':'H.264编码类型',
    'H.265':'H.265编码类型',
    'H.265编码类型':'H.265编码类型',
    '重量': '设备重量',
    '设备重量': '设备重量',
    }